services:
  - type: web
    name: inyko-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 4000
      - key: GROQ_API_KEY
        sync: false
